#!/usr/bin/env node

/*
 * parse command line argument
 */

var program = require('commander');
program.parse(process.argv);

var args = program.args;

const arg_0 = args[0];
//const arg_1 = args[1];
const fn = args[1];

var chatbot_name; // = ` ${arg_0}: `;
var user_name;
const resp = new Array();

//const fs = require('fs');

try {
    const buf = require('fs').readFileSync(fn, 'utf8');
    var lines = buf.split("\n");
    console.log("nlines", lines.length);
    lines.forEach((line, i) => {
        if (i == 0) {
            let foo = line.match(/] (.*): /);
            chatbot_name = foo[1];
            console.log("chatbot_name", chatbot_name);
        } else {
            let pos = line.indexOf(chatbot_name); // look for chatbot prompt

            var res = `*** ${pos} ${line}`;
            //console.log(line);
            if (pos > -1) {
                let ress = line.split(chatbot_name, 2);
                res = `${arg_0}: ${ress[1]}`;
            } else {
                //console.log("Before sleep 2000")
                //await sleep(3000);
                //(async () => await new Promise(resolve => setTimeout(resolve, 2000)))();
                // using async/await in top level
                //sleep(2000).then(msg => console.log(msg));
                // Sleep for 3 seconds
                //let ms = 2000;
                //Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, ms);
                //console.log("After  sleep")
                let ress = line.split(/] .*: /, 3);
                let foo = line.match(/] (.*): /);
                //console.log("--- res", ress);
                //console.log("=== foo", foo);
                user_name = foo[1];

                if (ress.length > 0) {
                    res = `${user_name}: ${ress[1]}`;
                }
                //console.log(res);
                resp.push(ress[1])
            }
        }

    })
    resp.forEach((r, i) => {
        console.log(i, r);
    })

} catch (err) {
    console.error(err);
}